// client/src/lib/components/Date.svelte
<script lang="ts">
    import Icon from "@iconify/svelte";
    import { formatDate } from "$lib/util/formatDate";
	import { onMount } from "svelte";

    const { date }: { date: string } = $props();
    let formattedDate = $state();
    
    onMount(() => {
        formattedDate = formatDate(date);
    })
</script>

<span class="date">
    <Icon icon="material-symbols:calendar-today" />
    <time datetime={date} title={date}>
        {formattedDate}
    </time>
</span>

<style>
    .date {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .date time {
        margin: 0 0 0 2px;
    }
</style>

// client/src/components/Date.vue
<template>
	<span class="date">
		<time :datetime="date" :title="date">
			{{ formattedDate }}
		</time>
	</span>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { formatDate } from "../util/formatDate";

const props = defineProps<{ date: string }>();
const formattedDate = ref("");
onMounted(() => {
	formattedDate.value = formatDate(props.date);
});
</script>

<style scoped>
.date {
	display: flex;
	justify-content: center;
	align-items: center;
	color: var(--text-primary);
	cursor: help;
}
</style>
