// client/src/lib/components/ThreadPreviewList.svelte
<script lang="ts">
	import type { ThreadModel } from "$lib/models/thread";
	import ThreadPreview from "./ThreadPreview.svelte";

	const { threadPreviewList }: { threadPreviewList: ThreadModel[] } = $props();
</script>

<ul>
	{#each threadPreviewList as threadPreview (threadPreview.id)}
		<li>
			<ThreadPreview threadPreview={threadPreview} />
		</li>
	{/each}
</ul>


<style>
	ul {
		list-style: none;
	}
</style>

// client/src/components/ThreadPreviewList.vue
<template>
	<ul>
		<li v-for="threadPreview in threadPreviewList" :key="threadPreview.id">
			<ThreadPreview :threadPreview="threadPreview" />
		</li>
	</ul>
</template>

<script setup lang="ts">
import ThreadPreview from "./ThreadPreview.vue";
import type { ThreadModel } from "@/models/thread";

const props = defineProps<{ threadPreviewList: ThreadModel[] }>();
</script>

<style scoped>
ul {
	width: 100%;
	list-style: none;
}

li {
	margin: 0 0 8px 0;
}
</style>
